#!/bin/bash --posix

#`$KOTLIN_HOME/bin/kotlinc-jvm out/jars/KaraExec.jar`

# determine where Kara is installed
export KARA_HOME="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# get the jars needed for the classpath
JARS="$KARA_HOME/lib/*.jar"
CP_JARS="$KARA_HOME/out/jars/KaraLib.jar:$KARA_HOME/out/jars/KaraExec.jar"
for JAR in $JARS
do
    case $JAR in
    *-sources.jar)
        ;;
    *-javadoc.jar)
        ;;
    *)
        CP_JARS="$JAR:$CP_JARS"
        ;;
    esac
done

java -DKARA_HOME="$KARA_HOME" -classpath "$CP_JARS" kara.namespace "$@"
