
require 'rake'

namespace :gen do

	desc "Generates the BodyTags.kt file with all of the main HTML tag classs"
	task :bodytags do
		require_relative 'src/kara/views/build_bodytags.rb'
		File.open('src/kara/views/BodyTags.kt.erb') do |infile|
			template = ERB.new infile.read, nil, '%<>'
			File.open('src/kara/views/BodyTags.kt', 'w') do |outfile|
				outfile.write template.result(binding)
			end
		end
	end
	
	desc "Generates the Enums.kt file with all of the CSS enumerations"
	task :css_enums do
		require_relative 'src/kara/styles/build_enums.rb'
		File.open('src/kara/styles/Enums.kt.erb') do |infile|
			template = ERB.new infile.read, nil, '%<>'
			File.open('src/kara/styles/Enums.kt', 'w') do |outfile|
				outfile.write template.result(binding)
			end
		end
	end

end